#cloud-config
hostname: debianVM
locale: en_US.UTF-8
chpasswd: { expire: False }
ssh_pwauth: True
packages: [git, sudo, locales]
users:
  - name: mzahorui
    passwd: '$6$aaGCkvzjJJSpP7KC$wYjYErBfQISfSu2OWJHwl6BgS0FbXuOWNt57FwBZq2gvMZiIzt4OsxftMxb8KaPt21dWlEXJpw/vJ0Db1f0R0/'
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    shell: /bin/bash
