virt-install \
  --connect qemu:///system \
  --name debian-server \
  --memory 4096 \
  --vcpus 4 --cpu host-passthrough \
  --os-variant debian13 \
  --disk size=20,backing_store=/home/masiyuan/Downloads/OS_ISO/debian-13-genericcloud-amd64.qcow2 \
  --cloud-init user-data="/home/masiyuan/.config/.dotfiles/user-data.yaml",meta-data="/home/masiyuan/.config/.dotfiles/meta-data" \
  --network type=default \
  --graphics none \
  --import
